/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package fr.squirrel.checksignature;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;

import android.content.Context;


@Kroll.module(name="Checksignature", id="fr.squirrel.checksignature")
public class ChecksignatureModule extends KrollModule
{
	
	public ChecksignatureModule()
	{
		super();
	}

	@Kroll.method
	public String getCertificateSHA1Fingerprint()
	{
		Context context = TiApplication.getAppCurrentActivity();
		if(context != null){
			return new CheckSign(context).getCertificateSHA1Fingerprint();	
		}
		return null;
		
	}

}

